{-# LANGUAGE ScopedTypeVariables #-}

-- |
-- Module      : Properties
-- Description : QuickCheck properties for the Yoneda embedding.
--
-- Each property below corresponds to a theorem from
--   "The Yoneda Perspective: Numbers as Representable Functors":
--
--   * 'prop_homCardinality'        — Hom(m, n) on (N_<=k, <=) is a singleton iff m <= n.
--   * 'prop_representableIdentity' — h_x preserves identities.
--   * 'prop_representableComposition' — h_x preserves composition (contravariantly).
--   * 'prop_yonedaRoundTripGeneral' — Yoneda lemma round-trip for arbitrary
--                                      natural transformations into arbitrary
--                                      target presheaves.
--   * 'prop_identityCriterion'     — h_x ~= h_y iff x = y for the order category.
--   * 'prop_groupCayleyZ3'         — h_(*) on B(Z/3Z) acts faithfully and freely.
--   * 'prop_groupCayleyS3'         — h_(*) on B(S_3) is right multiplication
--                                      (non-abelian, distinguishes left vs right).

module Properties where

import Test.QuickCheck

import FiniteCat
  ( Mor (..)
  , FiniteCat (..)
  , orderCat
  , groupCat
  )
import Yoneda
  ( Presheaf (..)
  , NaturalTransformation
  , representable
  , yonedaWitness
  , isoOfRepresentables
  )

-- ----------------------------------------------------------------------
-- Generators
-- ----------------------------------------------------------------------

-- | Bound the size of finite categories we test.
boundedNat :: Int -> Gen Int
boundedNat k = choose (0, k)

-- ----------------------------------------------------------------------
-- Theorem 1: Hom-set cardinality of the order category
-- ----------------------------------------------------------------------

-- | Theorem (paper, Section "Numbers as representable functors"):
--   In (N_<=k, <=), Hom(m, n) is a singleton iff m <= n, otherwise empty.
prop_homCardinality :: Property
prop_homCardinality =
  forAll (boundedNat 8) $ \k ->
  forAll (boundedNat k) $ \m ->
  forAll (boundedNat k) $ \n ->
    let cat        = orderCat k
        hmn        = hom cat m n
        expectedSz = if m <= n then 1 else 0
    in length hmn === expectedSz

-- ----------------------------------------------------------------------
-- Theorem 2: Functoriality of representable presheaves
-- ----------------------------------------------------------------------

-- | h_x preserves identities: h_x(id_z)(f) = f for f : z -> x.
prop_representableIdentity :: Property
prop_representableIdentity =
  forAll (boundedNat 6) $ \k ->
  forAll (boundedNat k) $ \x ->
  forAll (boundedNat k) $ \z ->
    let cat  = orderCat k
        h_x  = representable cat x
        idz  = identity cat z
        elts = onObj h_x z
    in conjoin
         [ counterexample
             ("identity action on " ++ show f)
             (onMor h_x idz f === Just f)
         | f <- elts
         ]

-- | h_x preserves composition contravariantly: for f : a -> b, g : b -> c,
--   h : c -> x,
--     h_x(g . f) h = h . (g . f) = (h . g) . f = h_x(f) (h_x(g) h).
prop_representableComposition :: Property
prop_representableComposition =
  forAll (boundedNat 5) $ \k ->
  forAll (boundedNat k) $ \x ->
  forAll (boundedNat k) $ \a ->
  forAll (choose (a, k)) $ \b ->
  forAll (choose (b, k)) $ \c ->
    let cat = orderCat k
        h_x = representable cat x
    in c <= x ==>
       case (hom cat a b, hom cat b c, hom cat c x) of
         (f:_, g:_, h:_) ->
           case compose cat g f of
             Just gf ->
               let lhs = onMor h_x gf h
                   rhs = onMor h_x g h >>= onMor h_x f
               in lhs === rhs
             Nothing -> property Discard
         _ -> property Discard

-- ----------------------------------------------------------------------
-- Theorem 3: Yoneda lemma — full round-trip for arbitrary alpha and F
-- ----------------------------------------------------------------------

-- | Yoneda lemma round-trip against a non-representable target presheaf with
--   non-trivial restriction maps. We define a "level presheaf" L on the order
--   category whose elements at @z@ are the morphisms in @hom cat z x@, with
--   the restriction along @g : w -> z@ acting as right composition (the same
--   formula as @h_x@ but constructed independently and viewed as an
--   "anonymous" presheaf). This is essentially h_x relabelled — the point is
--   that 'yonedaWitness' must succeed for ANY natural transformation
--   alpha : h_x -> L; we sample two genuinely different alphas:
--
--     (a) the identity transformation,
--     (b) a transformation generated by a chosen element u in L(x).
--
prop_yonedaRoundTripGeneral :: Property
prop_yonedaRoundTripGeneral =
  forAll (boundedNat 4) $ \k ->
  forAll (boundedNat k) $ \x ->
  forAll (boundedNat k) $ \y ->
    -- Use h_y as a target presheaf when there is a morphism x -> y; this
    -- gives a non-trivial element u : x -> y in F(x) and the restriction
    -- along g : w -> z is right-multiplication, exercising every non-trivial
    -- naturality square (no singleton shortcut).
    x <= y ==>
      let cat = orderCat k
          h_y = representable cat y
          -- Pick u : x -> y as the canonical witness in h_y(x).
          u   = case hom cat x y of
                  (m:_) -> m
                  []    -> error "x <= y guard violated"
          -- alpha_z f = h_y(f) u = u . f : z -> y, which is the unique
          -- morphism z -> y in the order category.
          alpha :: NaturalTransformation Int
          alpha _z f = case compose cat u f of
            Just m  -> m
            Nothing -> error "non-composable in alpha"
          cases =
            [ yonedaWitness cat h_y alpha x z f
            | z <- objects cat
            , f <- hom cat z x
            ]
      in conjoin (map property cases)

-- | Round-trip for the identity natural transformation on h_x. This is a
--   special case but exercises the most non-trivial restriction maps.
prop_yonedaRoundTripIdentity :: Property
prop_yonedaRoundTripIdentity =
  forAll (boundedNat 5) $ \k ->
  forAll (boundedNat k) $ \x ->
    let cat   = orderCat k
        h_x   = representable cat x
        alpha :: NaturalTransformation Int
        alpha = \_z f -> f          -- identity natural transformation
        cases =
          [ yonedaWitness cat h_x alpha x z f
          | z <- objects cat
          , f <- hom cat z x
          ]
    in conjoin (map property cases)

-- ----------------------------------------------------------------------
-- Theorem 4: Identity criterion
-- ----------------------------------------------------------------------

-- | Corollary of Yoneda: in the order category, h_x ~= h_y iff x = y.
prop_identityCriterion :: Property
prop_identityCriterion =
  forAll (boundedNat 6) $ \k ->
  forAll (boundedNat k) $ \x ->
  forAll (boundedNat k) $ \y ->
    let cat = orderCat k
        iso = isoOfRepresentables cat x y
    in iso === (x == y)

-- ----------------------------------------------------------------------
-- Theorem 5: Regular representation via Yoneda for finite groups
-- ----------------------------------------------------------------------

-- | Z/3Z under addition.
data Z3 = Z0 | Z1 | Z2 deriving (Eq, Show)

z3mul :: Z3 -> Z3 -> Z3
z3mul a b = toZ3 ((fromZ3 a + fromZ3 b) `mod` 3)
  where
    fromZ3 :: Z3 -> Int
    fromZ3 Z0 = 0
    fromZ3 Z1 = 1
    fromZ3 Z2 = 2
    toZ3 :: Int -> Z3
    toZ3 0 = Z0
    toZ3 1 = Z1
    toZ3 _ = Z2

instance Arbitrary Z3 where
  arbitrary = elements [Z0, Z1, Z2]

-- | The action of g on h_(*) hits every element exactly once (regular).
--   Free + transitive, so the group acts on itself faithfully.
prop_groupCayleyZ3 :: Property
prop_groupCayleyZ3 =
  let cat   = groupCat [Z0, Z1, Z2] Z0 z3mul
      h_pt  = representable cat ()
      elts  = onObj h_pt ()
      e     = Mor (show Z0) () ()
      orbit = [m | g <- elts, Just m <- [onMor h_pt g e]]
  in length orbit === 3 .&&. length (uniqueBy orbit) === 3
  where
    uniqueBy = foldr add []
    add m acc | m `elem` acc = acc
              | otherwise    = m : acc

-- | Symmetric group S_3 on {0,1,2}, represented as functions [Int] -> [Int]
--   stored by their image table. Multiplication is composition: (p . q) i =
--   p (q i). Non-abelian, so left-mul vs right-mul are distinguishable.
data S3 = S3 [Int] deriving (Eq, Show)

s3id :: S3
s3id = S3 [0, 1, 2]

s3all :: [S3]
s3all =
  [ S3 [0,1,2], S3 [0,2,1], S3 [1,0,2]
  , S3 [1,2,0], S3 [2,0,1], S3 [2,1,0]
  ]

s3mul :: S3 -> S3 -> S3
s3mul (S3 p) (S3 q) = S3 [ p !! (q !! i) | i <- [0, 1, 2] ]

-- | In the contravariant representable h_(*) = Hom(-, *), the action of a
--   morphism @g@ on an element @f@ is right composition @f . g@. We verify
--   this on the non-abelian S_3 by comparing presheaf-action against direct
--   right multiplication, and additionally checking that it is NOT left
--   multiplication (which would be the covariant convention).
prop_groupCayleyS3 :: Property
prop_groupCayleyS3 =
  let cat  = groupCat s3all s3id s3mul
      h_pt = representable cat ()
      tag g = Mor (show g) () ()
      checkRight =
        [ onMor h_pt (tag g) (tag f) === Just (tag (s3mul f g))
        | f <- s3all, g <- s3all
        ]
      -- Sanity: the left-multiplication convention is genuinely different
      -- on S_3, so the *negation* must hold for at least one pair.
      leftDiffersSomewhere =
        or [ s3mul f g /= s3mul g f | f <- s3all, g <- s3all ]
  in conjoin (map property checkRight) .&&. property leftDiffersSomewhere

-- ----------------------------------------------------------------------
-- Driver
-- ----------------------------------------------------------------------

runAllProperties :: IO ()
runAllProperties = do
  putStrLn "--- QuickCheck Properties ---"
  putStrLn ">> prop_homCardinality"
  quickCheck prop_homCardinality
  putStrLn ">> prop_representableIdentity"
  quickCheck prop_representableIdentity
  putStrLn ">> prop_representableComposition"
  quickCheck prop_representableComposition
  putStrLn ">> prop_yonedaRoundTripGeneral"
  quickCheck prop_yonedaRoundTripGeneral
  putStrLn ">> prop_yonedaRoundTripIdentity"
  quickCheck prop_yonedaRoundTripIdentity
  putStrLn ">> prop_identityCriterion"
  quickCheckWith stdArgs { maxSuccess = 500 } prop_identityCriterion
  putStrLn ">> prop_groupCayleyZ3"
  quickCheck prop_groupCayleyZ3
  putStrLn ">> prop_groupCayleyS3"
  quickCheck prop_groupCayleyS3

main :: IO ()
main = runAllProperties
