{-# LANGUAGE GADTs #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE RankNTypes #-}

-- | Identity types and the basic groupoid laws, encoded at the type level.
--
-- Haskell does not have proper dependent types, so we model the identity
-- type @a =_A b@ as a propositional GADT @Path a b@ with a single
-- constructor @Refl :: Path a a@. This corresponds to the J-rule's
-- foundational claim: every path is generated by reflexivity, and so
-- pattern-matching on @Refl@ is precisely the J-rule restricted to
-- non-dependent contexts.
--
-- Companion to: papers/05-hott/latex/05-hott.tex
module Path
  ( -- * Identity type
    Path (..)
    -- * Basic groupoid operations
  , refl
  , sym
  , trans
  , (.:)
  -- * Transport
  , transport
  -- * Congruence (action on paths)
  , ap
  -- * Equivalence
  , Equiv (..)
  , equivId
  , equivSym
  ) where

-- | The identity type. @Path a b@ is inhabited iff @a@ and @b@ are the same
-- type-level value (or more precisely: the type checker accepts @a ~ b@).
--
-- Agda-style:
--
-- > data _==_ {A : Set} : A -> A -> Set where
-- >   Refl : {a : A} -> a == a
data Path a b where
  Refl :: Path a a

-- | Reflexivity. Aliased to constructor for ergonomics.
refl :: Path a a
refl = Refl

-- | Symmetry of paths. Pattern matching on @Refl@ unifies @a@ and @b@.
--
-- Agda-style:
--
-- > sym : {A : Set} {a b : A} -> a == b -> b == a
-- > sym Refl = Refl
sym :: Path a b -> Path b a
sym Refl = Refl

-- | Transitivity. The proof works precisely because matching @p@ on @Refl@
-- forces @a ~ b@, after which @q :: Path b c@ becomes @Path a c@.
--
-- Agda-style:
--
-- > trans : {A : Set} {a b c : A} -> a == b -> b == c -> a == c
-- > trans Refl q = q
trans :: Path a b -> Path b c -> Path a c
trans Refl q = q

-- | Infix synonym for 'trans'.
(.:) :: Path a b -> Path b c -> Path a c
(.:) = trans
infixr 5 .:

-- | Transport along a path. In Haskell we cannot quantify over arbitrary
-- type-level predicates, so we model transport at the value level: given
-- a witness @Path a b@ and a value of "type-indexed-by-a", we get a value
-- "type-indexed-by-b". With GADT pattern-matching this is straightforward.
--
-- Agda-style:
--
-- > transport : {A : Set} (P : A -> Set) {a b : A} -> a == b -> P a -> P b
-- > transport P Refl x = x
transport :: forall p a b. Path a b -> p a -> p b
transport Refl x = x

-- | Action of a function on a path (the functor laws of paths).
--
-- In genuine HoTT, given @f : A -> B@ and @p : x =_A y@, we get
-- @ap f p : f x =_B f y@. Because our 'Path' equates type-level values
-- (not terms of a fixed type), the closest faithful encoding is: from a
-- proof @Path a b@ that the indices coincide we obtain @Path (f a) (f b)@.
-- Pattern-matching on @Refl@ unifies @a@ with @b@, after which
-- @Refl :: Path (f a) (f a)@ has the desired type.
--
-- Agda-style:
--
-- > ap : {A B : Set} (f : A -> B) {a b : A} -> a == b -> f a == f b
-- > ap f Refl = Refl
ap :: forall k l (f :: k -> l) (a :: k) (b :: k). Path a b -> Path (f a) (f b)
ap Refl = Refl

-- | A type equivalence, simplified to a pair of maps. In genuine HoTT
-- @Equiv A B@ also carries homotopies witnessing that the two maps are
-- mutual inverses; we cannot construct those total functions in Haskell
-- without dependent types, so we omit them rather than fill the slots
-- with @error@. The remaining @to@/@from@ pair is honest data, and the
-- accompanying QuickCheck properties (in @Properties.hs@ when present)
-- can stand in for the missing coherence at concrete types.
data Equiv a b = Equiv
  { equivTo   :: a -> b
  , equivFrom :: b -> a
  }

-- | The identity equivalence.
equivId :: Equiv a a
equivId = Equiv id id

-- | Inverse of an equivalence.
equivSym :: Equiv a b -> Equiv b a
equivSym (Equiv f g) = Equiv g f
